### ISSUE TITLE
qb-clothing

### ISSUE THREAD

**Issue by milamber54** [qbcore-framework/qbcore-redmproject#20]
After entering the character information, the outfit menu does not open, there is a problem

**Comment by milamber54** [comment]
[https://im.ge/i/TRvH39](url)

**Comment by RexShack** [comment]
see the same possibly a bit too early in the development stage

**Comment by ChatDisabled** [comment]
We are aware of that and it got broken again since we weren't 100% sure how we were going to do it. So it is still in development. Thanks for already doing bug testing!
